### ISSUE TITLE
struct.unpack raises struct.error: unpack requires a string argument of length ***

### ISSUE THREAD

**Issue by pedrohasselmann** [VIRTIS-VEX/VIRTISpy#1]
When I try to load VENUS-EXPRESS VIRTIS cubes I get:

> struct.error: unpack requires a string argument of length ***

The error occurs at this line:

> tmp2=struct.unpack((len(temp))*'HH',tmp2)

Do you have any idea where I could exactly modify it to have a proper reading?

**Comment by ghost** [comment]
Thank you for the use of VIRTISpy.
I will check the software and solve the problem.


Thank you

Romolo

--
******************************************
Romolo Politi, PhD
IAPS-INAF
Room U1A05
Via Fosso del Cavaliere 100
I00133 Rome
Italy
Phone: +39 06  49934710
Fax:    +39 06   49934188
E-Mail: romolo.politi@iaps.inaf.it
url: http://www.romolopoliti.com
skype: romolo_politi
******************************************

2017-07-11 17:33 GMT+02:00 Pedro H. Hasselmann <notifications@github.com>:

**Comment by pedrohasselmann** [comment]
Hi Romolo,

I have solved the problem and also implemented for ROSETTA. 
Check it out on my page.
I'm now fighting to make it read VIRTIS-H, do you have any hints where could I modify it?
